### ISSUE TITLE
Current card category is not shown correctly at terminal

### ISSUE THREAD

**Issue by BeshrABS** [humamAbedrabbo/ECS#11]
when there is a multiple category available at terminal, the "current card category" displayed at terminal is always "default" whatever it's current category!
![image](https://user-images.githubusercontent.com/86525682/125194445-05f7ec00-e25a-11eb-8edb-765f7954b099.png)

**Comment by humamAbedrabbo** [comment]
Category is not the category of card. Cards don't store categories.

**Comment by humamAbedrabbo** [comment]
To be fixed in later versions
