### ISSUE TITLE
some times the card scanning is stopped at terminal

### ISSUE THREAD

**Issue by BeshrABS** [humamAbedrabbo/ECS#12]
there is a situation where card reader timer stops working (reader LED is not blinking) randomly.
the situation can be recovered by logging-out and relogging-in.
i couldn't find fixed steps to reproduce the issue but it happens after charging cards and opening "CARD RECORD" and "SESSION HISTORY" windows several times.

**Comment by BeshrABS** [comment]
i had noticed that the issue happens when terminal's window loses focus, like oppenning calculator!

**Comment by humamAbedrabbo** [comment]
Not found
