### ISSUE TITLE
Game reader devices not activated

### ISSUE THREAD

**Issue by beshr-abs** [humamAbedrabbo/ECS#48]
the game reader devices are stopped after initialization using configuration cards (it's normal), but it never start after the web gui detects it.

**Comment by beshr-abs** [comment]
لا حظت أن البرنامج لم يتصل أصلا بأجهزة الألعاب!

**Comment by beshr-abs** [comment]
the readers were activated now, but only after restarting the service.

**Comment by mouinhourani** [comment]
You don't have to restart the service.   Did you refresh the card reader by clicking the refresh icon? it should solve the problem.

**Comment by beshr-abs** [comment]
I refreshed card readers and waited for a minute but nothing happened, i will add some readers to the system and try again.

**Comment by beshr-abs** [comment]
It's okay now.
Thanks.
