### ISSUE TITLE
Total Customers today in dasboard is  incorrect

### ISSUE THREAD

**Issue by beshr-abs** [humamAbedrabbo/ECS#52]
Total Customers today shown in dashboard is incorrect: I have on my test system only 6 customers with cards but it's displayed 12.
![image](https://user-images.githubusercontent.com/43375242/45918626-832bf980-be92-11e8-81d3-94fa9a6f8ff4.png)

**Comment by humamAbedrabbo** [comment]
@beshr-abs formula behind total customers is correct, would you please send me dump list of cards, postransaction and gamedevicetransactions to check if any non-integrated card numbers case occurred

**Comment by beshr-abs** [comment]
Here is a backup of the current DB.
[ECS.zip](https://github.com/humamAbedrabbo/ECS/files/2413924/ECS.zip)

**Comment by beshr-abs** [comment]
It's okay now.
Thank you.
