### ISSUE TITLE
Some records are not collected form game devices

### ISSUE THREAD

**Issue by beshr-abs** [humamAbedrabbo/ECS#56]
I noticed that one record is not collected from one game device, the system got the records before and after it.
so the sum of points sold at terminal is less than the points collected at game readers.

**Comment by mouinhourani** [comment]
Can you please provide me with more details about this issue so we can repeat it again. We have to run this issue to figure out what is the problem.

**Comment by humamAbedrabbo** [comment]
@beshr-abs  I would suggest to send us a database backup so we can analyse the transactions

**Comment by beshr-abs** [comment]
https://github.com/humamAbedrabbo/ECS/issues/52#issuecomment-424214259

**Comment by mouinhourani** [comment]
I attached the database you sent, and I checked all the record numbers in table GameReaderDeviceTransactions for your three devices, but I didn't found any missing record.  
The program save device record number at column [DeviceTransactionId].  So what is the number of the missing record( the number you get from the device)?

**Comment by beshr-abs** [comment]
check the total amount of money collected at the terminals and the amount collected at game devices you will find a difference by 475 (game2 price).

**Comment by beshr-abs** [comment]
i tested it on the new version and it's okay now :)
Thanks.

**Comment by beshr-abs** [comment]
The issue happened again!
may there is a timeout.

**Comment by humamAbedrabbo** [comment]
@mouinhourani can you please check this with @beshr-abs

**Comment by beshr-abs** [comment]
The issue is here again i have attached an excel sheet with the records from the system and from my devices using my tools.
the record count is the same but the total in report is incorrect!
[Records comparism.xlsx](https://github.com/humamAbedrabbo/ECS/files/2492730/Records.comparism.xlsx)

**Comment by humamAbedrabbo** [comment]
@mouinhourani Any information we can obtain from attached data report regarding the bug

**Comment by mouinhourani** [comment]
Could you please tell me where rows have different in total between the two sheets?
Also "The record from sheet" did you copy it from database?
Thanks,

**Comment by beshr-abs** [comment]
One of the two sheets in the Excel sheet was copied for the DB and the other was collected by out tools, it will try to clear cards , terminal sessions and game reader transactions then I will retry to reproduce the problem

**Comment by mouinhourani** [comment]
Thanks, be sure that the field "DeviceTransactionId" from database is included in the sheet

**Comment by mouinhourani** [comment]
Sorry I sent it the previous note from a different account

**Comment by beshr-abs** [comment]
Seems like we have to add the record with the result 23 to the game playing records.
can you help me to add it?

**Comment by beshr-abs** [comment]
it's okay now, thanks.
