### ISSUE TITLE
Black list on game devices not working

### ISSUE THREAD

**Issue by beshr-abs** [humamAbedrabbo/ECS#57]
When adding a user card to blacklist, it was detected at the cashier but not detected at game devices even after refreshing the game devices and restarting the service.

**Comment by humamAbedrabbo** [comment]
@mouinhourani It seems that there are two causes of the issue, calling add blacklist function through a non awaited thread, and pass a null model to the hardware function

**Comment by mouinhourani** [comment]
For terminal there is no problem with backlist
