### ISSUE TITLE
Balance at Cutomers page

### ISSUE THREAD

**Issue by beshr-abs** [humamAbedrabbo/ECS#58]
The balance displayed at customers page should be the current balance (points charged - points used at game devices).

**Comment by humamAbedrabbo** [comment]
@beshr-abs the balance is not calculated in the view, it is stored in card record and gets updated in two situations: when card is charged, the balance will be updated, and when new wifi transaction registered, then the balance will subtract the transaction points amount. Any variation in the balance from its expected value could mean missing downloaded wifi transactions (Udp lost packets is a suspect case here)
