### ISSUE TITLE
Company name in page title is incorrect

### ISSUE THREAD

**Issue by beshr-abs** [humamAbedrabbo/ECS#63]
Please change our company name in page title from SMSG to SCSG.

**Comment by humamAbedrabbo** [comment]
hi beshr,
latest commit now includes the modification for #63

**Comment by humamAbedrabbo** [comment]
Is this still open?

**Comment by beshr-abs** [comment]
It's okay now.
but please correct company name at the footer: "Easy Pay System © 2018 SMART CARD SOLUTION GROUP "

**Comment by humamAbedrabbo** [comment]
it is exactly SMART CARD SOLUTION GROUP, is there a change of that? if it shows different value then you should update server

**Comment by beshr-abs** [comment]
SMART CARD SOLUTION**S** GROUP

**Comment by humamAbedrabbo** [comment]
done
