### ISSUE TITLE
Added or removed cards from blacklist not work on casheir until resrart the app

### ISSUE THREAD

**Issue by beshr-abs** [humamAbedrabbo/ECS#64]
Blacklist in terminals is not updated until the app is restarted.

**Comment by humamAbedrabbo** [comment]
this is not related to restart issue. The card will be checked once loaded on card reader, if at that moment, the card server record didn't get updated from the WiFi, then nothing can be done.

**Comment by beshr-abs** [comment]
I'm sure now that the Terminal doesn't recognize changes in blacklist until it's restarted.
the card is black listed in the db but the terminal accepts to charge it.
at the same time game reader devices show that the card is blacklisted and clears it's balance.

**Comment by beshr-abs** [comment]
هل من جديد هنا؟

**Comment by humamAbedrabbo** [comment]
waiting for your test results? testing blacklisted card in terminal without chance to put it in cache

**Comment by beshr-abs** [comment]
I have tested it: when a black listed card is used on a terminal form first time in a session it's recognized as black listed and still recognized as blacklisted if it's removed in the same session, also if am normal card is used first in the session it still normal when it's added to the black list in the same session.
seems to be cashing issue.

**Comment by humamAbedrabbo** [comment]
done. test it now!

**Comment by beshr-abs** [comment]
It's okay now, but the terminal are slightly slower.
Thanks.
