### ISSUE TITLE
A bigger font in terminal is needed

### ISSUE THREAD

**Issue by beshr-abs** [humamAbedrabbo/ECS#65]
the font in terminal is slightly small, it's hard to be seen in 7 inch devices.
![image](https://user-images.githubusercontent.com/43375242/46741549-eea50200-ccad-11e8-909a-b527b604f9b6.png)

**Comment by humamAbedrabbo** [comment]
i see the fonts are ok, whitch items do you think have to change?

**Comment by beshr-abs** [comment]
Category names (the orange buttons) is the most important.

**Comment by beshr-abs** [comment]
هل من جديد هنا؟

**Comment by beshr-abs** [comment]
The font size in terminal is perfect.
thanks.
