### ISSUE TITLE
A confirmation message on deleting items is needed

### ISSUE THREAD

**Issue by beshr-abs** [humamAbedrabbo/ECS#66]
It would be better to add a confirmation message when delete button is pressed in Games, Readers , Users , Sites, Terminals, Categories, PLUs.

**Comment by humamAbedrabbo** [comment]
done. Please check!

**Comment by beshr-abs** [comment]
It's okay now,Thanks.
I tried "dotnet publish source/MyApp.Web --output published-app --configuration Release"
but the result was an old result , i used visual studio to get a new one
