### ISSUE TITLE
Pagination in game reader reading mistake

### ISSUE THREAD

**Issue by beshr-abs** [humamAbedrabbo/ECS#68]
Pagination in game reader reading is redirecting to games page not to the next page in game reader readings.

**Comment by humamAbedrabbo** [comment]
dobe

**Comment by beshr-abs** [comment]
now the pagination in all pages don't work!

**Comment by humamAbedrabbo** [comment]
try update, this is working fine in latest updates

**Comment by beshr-abs** [comment]
I have tried it, it working only in Gage readers readings page only!

**Comment by humamAbedrabbo** [comment]
done

**Comment by beshr-abs** [comment]
it's okay now.
thanks.
