### ISSUE TITLE
Error in Tarminals page

### ISSUE THREAD

**Issue by beshr-abs** [humamAbedrabbo/ECS#70]
A user in terminal logged in and the system shutdown, the user did't log in again but in terminals page he is displayed as logged in.
![image](https://user-images.githubusercontent.com/43375242/46916803-4a320100-cfc8-11e8-94c0-d17f78c8aade.png)
in the dashboard no active terminals:
![image](https://user-images.githubusercontent.com/43375242/46916811-6635a280-cfc8-11e8-8b23-63d8620aa619.png)

**Comment by beshr-abs** [comment]
The problem happens when the terminal app crashes (the app crash when a charged card from outside the system is used!)!
and the user still seems to be logged in after that.

**Comment by humamAbedrabbo** [comment]
Login in new session, then logout
