### ISSUE TITLE
Calculated cards balance in customers page is incorrect

### ISSUE THREAD

**Issue by beshr-abs** [humamAbedrabbo/ECS#71]
Card balance shown in "Customer Cards" page is incorrect, many of them is negative!
![image](https://user-images.githubusercontent.com/43375242/46917022-11dff200-cfcb-11e8-9440-d52060469895.png)
up to now we are using point value is one pound.

**Comment by beshr-abs** [comment]
هل من جديد هنا؟

**Comment by beshr-abs** [comment]
it still negative for all customers, i think there is an error in calculations.

**Comment by beshr-abs** [comment]
I have retested it now.
![image](https://user-images.githubusercontent.com/43375242/47258311-1eb88600-d4a2-11e8-8ed6-29c0f1472e9f.png)
A DB backup:

[ECS-20181020-20-0-14.zip](https://github.com/humamAbedrabbo/ECS/files/2498363/ECS-20181020-20-0-14.zip)

**Comment by beshr-abs** [comment]
I used the following test:
charge cards 10000 point-> customers balance okay.
use games 9900 point-> customers balance okay.
charge cards again 10000 point-> customer balance okay.
use games 9900 point-> customer balance is negative -9800 !

**Comment by beshr-abs** [comment]
I have noticed that the issue now occures with records in game readers when the server is off, when the server is on again the records are collected correctly and the reports are correct but customer balance are incorrect, it's corrected only when a new game readers records are collected.

**Comment by beshr-abs** [comment]
The issue still happen when cards are used in game devices when server is off.

**Comment by humamAbedrabbo** [comment]
done!, please update server and terminal

**Comment by beshr-abs** [comment]
It's okay now.
Thanks.
