### ISSUE TITLE
Calcutated usage in Sites page seems to be incorrect

### ISSUE THREAD

**Issue by beshr-abs** [humamAbedrabbo/ECS#72]
The usage in "Sites" page seems to be incorrect!
![image](https://user-images.githubusercontent.com/43375242/46917180-7b143500-cfcc-11e8-816b-3e7911e588d1.png)

![image](https://user-images.githubusercontent.com/43375242/46917184-8a937e00-cfcc-11e8-813e-5ca9ae10f0b8.png)

**Comment by humamAbedrabbo** [comment]
done

**Comment by beshr-abs** [comment]
It still incorrect, it's stuck at zero now!

**Comment by humamAbedrabbo** [comment]
which zero in snapshot? usages are: 60, 80, 20

**Comment by beshr-abs** [comment]
Games coverage and site usage are zero now!
![image](https://user-images.githubusercontent.com/43375242/47258328-6b9c5c80-d4a2-11e8-9010-fc0a0cc07a74.png)
![image](https://user-images.githubusercontent.com/43375242/47258329-76ef8800-d4a2-11e8-8e27-6bce3c046df2.png)
The DB backup is in attached in #71

**Comment by beshr-abs** [comment]
هل من جديد هنا؟

**Comment by beshr-abs** [comment]
Site usage is still zero!

**Comment by beshr-abs** [comment]
it's okay now thanks.
