### ISSUE TITLE
Terminal Application crashes

### ISSUE THREAD

**Issue by beshr-abs** [humamAbedrabbo/ECS#73]
Terminal application  crashes when a cars with balance (from outside the system) is used.
it shouldn't crash but should give a warning or refuse to charge it and (or) add it to black list (i don't know what is the best to do here) but at list it shouldn't crash

**Comment by humamAbedrabbo** [comment]
@mouinhourani  please can you check this situation

**Comment by mouinhourani** [comment]
What is the lock of this card?

**Comment by beshr-abs** [comment]
The default lock, in the current test I didn't change cards lock

**Comment by mouinhourani** [comment]
How come that anyone could initial and charge cards outside the system with your default lock? This lock is very secure and we didn't discuss the issue that someone else has this lock.

**Comment by beshr-abs** [comment]
That's true but the terminal shouldn't crash, maybe it should refuse to share the card, or notify the user to reset the card first, .....

**Comment by beshr-abs** [comment]
It's okay now, thanks.
could you please display a message box to inform the user that the card's balance will be cleared first?

**Comment by beshr-abs** [comment]
it's okay now thanks.
could you please display a message box to inform the cashier that the card's balance will be cleared first before charging it?
