### ISSUE TITLE
Warning message for cards charged from outside

### ISSUE THREAD

**Issue by beshr-abs** [humamAbedrabbo/ECS#75]
I think that there is a need for warning message when a card with balance and not registered in DB is used at terminal app:

- "Card issued from outside the system it will be cleared before charging!".

- "بطاقة من خارج المنشأة سيتم مسحها قبل أي عملية".

**Comment by beshr-abs** [comment]
The message is shown for all new cards even if it's without balance!

**Comment by humamAbedrabbo** [comment]
done

**Comment by beshr-abs** [comment]
Now when i use a new ans cleared card om the terminal the card is initialized and charged then a message "Card issued from outside the system it will be cleared before charging!" is shown the the terminal clear it again before recharging!

**Comment by beshr-abs** [comment]
Seems to be okay now.
under testing.
thanks.

**Comment by beshr-abs** [comment]
when issuing cards of categories of special cashiers the warning message of cards from outside the system pops up, and the card is charged but not registered in the DB (same issue).

**Comment by humamAbedrabbo** [comment]
@mouinhourani would you please have a look on this case! Special cashiers

**Comment by beshr-abs** [comment]
I have retested it now: the issue happens with non extendable validity categories.

**Comment by mouinhourani** [comment]
You mean that if we try to charge a card with non extendable validity categories we get always this message "Card issued from outside the system it will be cleared before charging!".  Is there any different between the card is expired or not?
Please send to us all the details of this card's category.

**Comment by humamAbedrabbo** [comment]
@beshr-abs it looks you need to be more specific about the case the ended up failing with this error message

**Comment by mouinhourani** [comment]
Done
