### ISSUE TITLE
A limit is needed to termenal card charge amount

### ISSUE THREAD

**Issue by beshr-abs** [humamAbedrabbo/ECS#79]
There should be a limit to maximum point amount charged to user card it, i suggest to fix it to 60000 point since the charge amount in the USB device is represented in two Bytes (although the card balance is represented in card by 3 Bytes).
The issue happened when i tried to charge a card at terminal by 100K point but the cared was charged to about 30K point.
Also there should be a maximum point amount stored in user card (ex. 100K point) it can be added the system settings, the terminals shouldn't allow to charge user cards beyond this value.

**Comment by humamAbedrabbo** [comment]
@mouinhourani can we insert a validation message box

**Comment by mouinhourani** [comment]
sure

**Comment by humamAbedrabbo** [comment]
done

**Comment by beshr-abs** [comment]
there is a need to only limit the maximum amount of card charge to be 60000 point only, no need to limit the card balance.
also it's important that this limitation wont make price of points to be incorrect i.e if the category id 3000 point->1000 pound and the operation is 63000 point->21000pound the result invoice will be 60000point->20000pound.

**Comment by mouinhourani** [comment]
Done
