### ISSUE TITLE
All cards categories should be resettable from all casheirs

### ISSUE THREAD

**Issue by beshr-abs** [humamAbedrabbo/ECS#80]
We noticed that non dynamic categories cards can't be rested from normal cashiers.

**Comment by mouinhourani** [comment]
Did you test it with dynamic option = true and all cashier = false?

**Comment by humamAbedrabbo** [comment]
@beshr-abs  Is this still opened?

**Comment by beshr-abs** [comment]
I'm sorry non dynamic categorized card are can be reseted from all cashiers, okay the true issue is that the cards of special cashiers cannot be reseted  from all cashiers, is that possible?

**Comment by mouinhourani** [comment]
This is correct "the cards of special cashiers cannot be reseted from all cashiers". It's reseted, charged and initialed just from master cashier. These cards need high permission to deal with not for all users
