### ISSUE TITLE
Deactivating Site Games

### ISSUE THREAD

**Issue by beshr-abs** [humamAbedrabbo/ECS#81]
When inactivating site games the inactive game count in sites table, dashboard,,games,readers is incorrect.
Also it's uncomfortable to enter WiFi password when activating or deactivating site games.

**Comment by beshr-abs** [comment]
1. when activating or deactivating a site all reader in that site should be deactivated.
2. when adding a new game to a site the game activity status should be like it's parent sites.
3. when changing the site's settings no need to enter it's password again if it's not changed.

**Comment by beshr-abs** [comment]
I'm testing it now , but their is a related issue: When deactivating a reader from reads page then i reactivate it again it never activate physically until i issue a configuration card for it!
although i activated site games and reactivated them and it worked.

**Comment by humamAbedrabbo** [comment]
done

**Comment by beshr-abs** [comment]
I have tested it:
- Activating and deactivating sites is working and usage at dashboard and active game count is correct 👍.
- Activating and deactivating game readers is working and usage at dashboard and active game count is correct but if a game with two readers and one of them is deactivating the active game count is not decreased and inactive game count is increased (it's not totally incorrect behavior).

**Comment by humamAbedrabbo** [comment]
Done, in addition to add orange color for semi active games.
active game is when any reader is active
semi active game is when any reader is not active
inactive game is when all readers are not active
reader active means can accept payment and not out of service

**Comment by beshr-abs** [comment]
I suggest (if possible) to color the games in "Game Status" at dashboard as following:
- green : if all readers are connected and active.
- red : if all readers are connected and deactivated.
- orange: if there is one reader at least connected and activated.
- gray : if all readers are disconnected.
i don't' think that other colors and possibilities will add any more useful details.
also if we return it to show only connectivity status is okay.

**Comment by humamAbedrabbo** [comment]
done!

**Comment by beshr-abs** [comment]
protected Dictionary<string, GameStatusType> GameStatus()
        {
           var results = DeviceCommService.CommDictionary.Values.ToList();

            var dic = new Dictionary<string, GameStatusType>();
            foreach(var g in games)
            {
                var allActive = g.GameReaders.All(x => x.IsActive);
                var oneActive = g.GameReaders.Any(x => x.IsActive);
                var gDevices = results.Where(x => x.GameId == g.Id);
                if(allActive)
                {
                    if(gDevices.All(x => x.IsConnected))
                        dic[g.Name] = GameStatusType.GREEN;
                    else if(gDevices.Any(x => x.IsConnected))
                        dic[g.Name] = GameStatusType.ORANGE;
                    else
                        dic[g.Name] = GameStatusType.GREY;
                }
                else
                if (oneActive)
                {
                    if (gDevices.Any(x => x.IsConnected))
                        dic[g.Name] = GameStatusType.ORANGE;
                    else
                        dic[g.Name] = GameStatusType.GREY;
                }
                else
                {
                    if (gDevices.All(x => x.IsConnected))
                        dic[g.Name] = GameStatusType.RED;
                    else if(gDevices.Any(x => x.IsConnected))
                        dic[g.Name] = GameStatusType.ORANGE;
                    else
                    dic[g.Name] = GameStatusType.GREY;
                }
            }
            return dic;
        }

**Comment by beshr-abs** [comment]
Now i noticed that when one game reader of game is disconnected the other is shown in readers page as disconnected although the status in dashboard is correct (it's orange).

**Comment by beshr-abs** [comment]
Hello
when i do the following : 1- deactivate a site - 2-adcivate a reader of game with two readers - 3- after restarting the server all readers of this site are deactivating but it's shown as activated and it cannot be activated by refreshing readers, the only way is by reactivating the site

**Comment by humamAbedrabbo** [comment]
Let me check this with @mouinhourani

**Comment by beshr-abs** [comment]
Also i prefer if you put site Activate and deactivate buttons besides each other not on on top one.

**Comment by humamAbedrabbo** [comment]
Hi bisher, i patched a fix that i think will resolve this issue

**Comment by humamAbedrabbo** [comment]
FYI @beshr-abs @mouinhourani

**Comment by beshr-abs** [comment]
the issue isn't solved completely, when i disable site readers are disabled, then when i enable the readers they are enabled, next when i do a "Refresh Readers" they are re disabled here the deactivated games is 0(which is not true).

**Comment by humamAbedrabbo** [comment]
Can we try now @beshr-abs

**Comment by humamAbedrabbo** [comment]
@beshr-abs added the device refresh

**Comment by beshr-abs** [comment]
It's okay now, Thanks.
