### ISSUE TITLE
A card transactions report

### ISSUE THREAD

**Issue by beshr-abs** [humamAbedrabbo/ECS#82]
We need a card transaction report to be added like this:
- search criteria : card number(if possible) - date from - date to.
- result fields : cards number - category (not mandatory) - user name - date - time - amount - card balance(not mandatory) - transaction type (Play Session or Card charge)- game - terminal.

the results should be ordered by card number (if the report is not for one card) then by date-time

**Comment by humamAbedrabbo** [comment]
done

**Comment by humamAbedrabbo** [comment]
Card report updated to include Customer Name instead of Session User Name

**Comment by humamAbedrabbo** [comment]
It is there already, try to delete the report row from database and re run the server, it will create it again

**Comment by beshr-abs** [comment]
it's okay now, thanks.
